### ISSUE TITLE
Not able to update non-primitive storage data from constructor

### ISSUE THREAD

**Issue by ashutoshvarma** [ask-lang/ask#246]
## Problem
Contracts which modify `Mapping` during their contract constructor fails to deploy.

### Example contract
Below contract fails to deploy, on any node.
```ts
import { HashKeccak256, AccountId, Mapping, u128, ZERO_ACCOUNT } from "ask-lang";

@spreadLayout()
class Data {
  map: Mapping<AccountId, u128, HashKeccak256> = new Mapping();
}

@contract()
export class Contract {
  data: Data;

  constructor() {
    this.data = new Data();
  }

  @constructor()
  default(): void {
    // modify the mapping
    this.data.map.set(ZERO_ACCOUNT, u128.One);    // works if this is commented out.
  }

  @message()
  get(account: AccountId): u128 {
    return this.data.map.get(account);
  }
}
```

**Comment by yjhmelody** [comment]
Very strange. You see that erc20 example could set storage in `default`

**Comment by ashutoshvarma** [comment]
I did see the ERC20 example, but it does not set `Mapping`.  If you add the below line in ERC20 example constructor, it fails at deployment.
```ts
this.storage.balances.set(ZERO_ACCOUNT, u128.One);
```

The issue is with `Mapping` type probably.

**Comment by yjhmelody** [comment]
I will check this issue after updating deps.

**Comment by ashutoshvarma** [comment]
@yjhmelody 
I figured out this issue, problem is with key generation for `Mapping` (an other similar types).

https://github.com/ask-lang/ask/blob/630b2dbc8266997918e6f5766f05440f2bad4e7a/as-packages/lang/assembly/collections/mapping.ts#L15-L25

When we call `Mapping.set()` from inside the ask! constructor, the ` _key: Key | null` is still `null` as its `pullSpread()`/`pushSpread()` is never called on it before therefore `this._key!.toBytes()` panics 


Here is the deploy function generated by ask! transform,

```ts
  deploy<__M extends __lang.IMessage>(message: __M): i32 {
    if (message.isSelector(Contract.defaultSelector)) {
      this.default();    // -------> Mapping's _key is still null, so panics
    }
    __lang.pushSpreadRoot(this, __lang.Key.zero());
    return 0;
  }
````

**Comment by yjhmelody** [comment]
Yeah, The design for `deploy` never call `pullSpreadRoot` firstly, maybe it's not good.

**Comment by yjhmelody** [comment]
@ashutoshvarma it seems should be fixed by calling `pullSpreadRoot`.

**Comment by ashutoshvarma** [comment]
@yjhmelody we can change the deploy function to something like this. I think it will be fine for most cases.

```ts
  deploy<__M extends __lang.IMessage>(message: __M): i32 {
    // save the contract
    __lang.pushSpreadRoot(this, __lang.Key.zero());
    
    // pull contract
    const contract = __lang.pullSpreadRoot(__lang.Key.zero());
    if (message.isSelector(Contract.defaultSelector)) {
      contract.default();   
    }
    __lang.pushSpreadRoot(contract, __lang.Key.zero());
    return 0;
  }
```

**Comment by yjhmelody** [comment]
@ashutoshvarma Welcome to make a PR. But why call `__lang.pushSpreadRoot(this, __lang.Key.zero());`

**Comment by ashutoshvarma** [comment]
To save the contract state after the `contract.default();` call.
