### ISSUE TITLE
How to use ask!

### ISSUE THREAD

**Issue by trilloc** [ask-lang/ask#83]
Hi Folks,

Sorry for the noob question here. Can I have one example of how to use ask! to implement a smart contract in AssemblyScript on Substrate please?

Thank you in advance!

Cheers
Rajesh

**Comment by yjhmelody** [comment]
Hi, we are writing the docs

**Comment by masafumimori** [comment]
@yjhmelody 
Is the doc ready yet?

**Comment by koushiro** [comment]
@masafumimori  It will be release this weekend.

**Comment by masafumimori** [comment]
@koushiro 
Fantastic!
Do you know SwankyCLI will also support ask?
I tried to run `swanky init test` and chose "Ask!" for the framework and it threw an error saying `Sorry, ask is not supported yet`

**Comment by koushiro** [comment]
> Do you know SwankyCLI will also support ask? I tried to run `swanky init test` and chose "Ask!" for the framework and it threw an error saying `Sorry, ask is not supported yet`

No, I don't know.

**Comment by masafumimori** [comment]
@koushiro 
Hey! Where can I find the doc?
It should be available now according to what you mentioned?
> @masafumimori It will be released this weekend.

**Comment by iamizumi** [comment]
@masafumimori sorry about that.
We found that Ask! is not compatible with the latest metadata of pallet-contracts last week, so the documentation isn't all done yet.
I'll let you know once it's done, it should be ready this week 🤣
